Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "eloteste"
  config.vm.synced_folder "/home/elbgre/Documentos/eloteste/vagrant/scripts/", "/home/vagrant/scripts/" 
  config.vm.network "forwarded_port", guest: 3000, host: 3000
  config.vm.network "private_network", ip: "192.168.62.2"
  config.vm.provision "shell", path: "docker.sh"
  config.vm.provision "shell", path: "minikube.sh"
    config.vm.provider "virtualbox" do |box|
      box.name = "eloteste"
      box.memory = 8192
      box.cpus = 4
    end
end